-- ============================================================
-- TABLE: outbox_events
-- ============================================================
-- Implements the Outbox pattern for reliable event publication.
-- All events generated by FlightOps are stored here before publishing.
create table if not exists flight_operations.outbox_events (
    event_id uuid primary key,
    aggregate_type varchar(100) not null,
    aggregate_id varchar(100) not null,
    event_type varchar(100) not null,
    topic_name varchar(255) not null,
    event_key varchar(255) not null,
    payload jsonb not null,
    occurred_at timestamptz not null,
    published_at timestamptz,
    status varchar(30) not null,
    retry_count integer not null default 0
);

create index if not exists idx_outbox_events_status_occurred_at
    on flight_operations.outbox_events (status, occurred_at);

create index if not exists idx_outbox_events_aggregate
    on flight_operations.outbox_events (aggregate_type, aggregate_id);