services:
  prometheus:
    image: prom/prometheus
    container_name: flightops-prometheus

    ports:
      - "9090:9090"

    volumes:
      - /home/brian/dev/flight-ops-platform/infrastructure/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro